
name: 🚀 Deploy KoHiCo to reg.ru

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: ./app/yarn.lock
        
    - name: 📦 Install dependencies
      run: |
        cd app
        yarn install --frozen-lockfile
        
    - name: 🔨 Build Next.js application
      run: |
        cd app
        yarn build
        
    - name: 📋 Create deployment package
      run: |
        # Создаем директорию для деплоя
        mkdir -p deploy-output
        
        # Копируем статические файлы Next.js
        cp -r app/.next/static deploy-output/
        cp -r app/.next/standalone deploy-output/ 2>/dev/null || true
        cp -r app/public deploy-output/
        
        # Копируем готовые HTML файлы для быстрого деплоя
        if [ -d "deploy_package_REAL" ]; then
          cp -r deploy_package_REAL/* deploy-output/
        fi
        
        # Создаем файл .htaccess для правильной работы на Apache
        cat > deploy-output/.htaccess << 'EOF'
        DirectoryIndex index.html index.htm index.php
        
        <IfModule mod_rewrite.c>
        RewriteEngine On
        
        # Маршрутизация для каталога
        RewriteRule ^catalog/?$ catalog.html [L]
        RewriteRule ^brands/?$ index.html#brands [L,R=301]
        
        # Обработка остальных запросов
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /index.html [L]
        </IfModule>
        
        # Кэширование статических файлов
        <IfModule mod_expires.c>
          ExpiresActive On
          ExpiresByType text/css "access plus 1 month"
          ExpiresByType application/javascript "access plus 1 month"
          ExpiresByType image/png "access plus 1 month"
          ExpiresByType image/jpg "access plus 1 month"
          ExpiresByType image/jpeg "access plus 1 month"
        </IfModule>
        
        # Сжатие файлов
        <IfModule mod_deflate.c>
          AddOutputFilterByType DEFLATE text/html text/css application/javascript
        </IfModule>
        EOF
        
        # Создаем robots.txt
        cat > deploy-output/robots.txt << 'EOF'
        User-agent: *
        Allow: /
        
        Sitemap: https://www.kohico.ru/sitemap.xml
        EOF
        
        # Показываем что создалось
        echo "📁 Deployment package contents:"
        ls -la deploy-output/
        
    - name: 📤 Deploy via FTP to reg.ru
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy-output/
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.next/cache/**
          **/.logs/**
        
    - name: 🔄 Alternative: Deploy via SSH (if FTP fails)
      if: failure()
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Переходим в директорию сайта
          cd ${{ secrets.SITE_DIRECTORY }}
          
          # Клонируем или обновляем репозиторий
          if [ -d ".git" ]; then
            git pull origin master
          else
            git clone https://github.com/Yuriuser1/KoHiCo.git .
          fi
          
          # Устанавливаем зависимости и собираем проект
          cd app
          yarn install
          yarn build
          
          # Перезапускаем приложение (если используется PM2)
          pm2 restart kohico || pm2 start yarn --name "kohico" -- start
          
    - name: ✅ Deployment Success Notification
      if: success()
      run: |
        echo "🎉 KoHiCo успешно задеплоен на www.kohico.ru!"
        echo "📅 Дата: $(date)"
        echo "🔗 Сайт: https://www.kohico.ru"
        
    - name: ❌ Deployment Failure Notification  
      if: failure()
      run: |
        echo "❌ Ошибка деплоя KoHiCo"
        echo "📅 Дата: $(date)"
        echo "🔧 Проверьте секреты GitHub и доступы к серверу"
